### ISSUE TITLE
TP Emblem Checklist

### ISSUE THREAD

**Issue by SpookyThunder** [SpookyThunder/Tortured-Planet#6]
Check off as you go

- [ ] Sunshine Atoll Act 1
- [ ] Sunshine Atoll Act 2
- [ ] Sunshine Atoll Act 3
- [ ] Eruption Conduit Act 1
- [ ] Eruption Conduit Act 2
- [ ] Eruption Conduit Act 3
- [ ] Drowned Downtown Act 1
- [ ] Drowned Downtown Act 2
- [ ] Drowned Downtown Act 3
- [ ] Snowcap Nimbus Act 1
- [ ] Snowcap Nimbus Act 2
- [ ] Snowcap Nimbus Act 3
- [ ] Gritty Columns Act 1
- [ ] Gritty Columns Act 2
- [ ] Gritty Columns Act 3
- [ ] Fume Shaft Act 1
- [ ] Fume Shaft Act 2
- [ ] Fume Shaft Act 3
- [ ] Liftoff Gantry Act 1
- [ ] Liftoff Gantry Act 2
- [ ] Liftoff Gantry Act 3
- [ ] Spacewalk Act 1
- [ ] Spacewalk Act 2
- [ ] Spacewalk Act 3
- [ ] Alien Armageddon Act 1
- [ ] Alien Armageddon Act 2
- [ ] Alien Armageddon Act 3
- [ ] Star Showdown

**Comment by JonBax** [comment]
All emblems added. All that is left is to test them.

- [ ] Sunshine Atoll Act 1
- [ ] Sunshine Atoll Act 2

- [ ] Eruption Conduit Act 1
- [ ] Eruption Conduit Act 2

- [ ] Drowned Downtown Act 1
- [ ] Drowned Downtown Act 2

- [ ] Snowcap Nimbus Act 1
- [ ] Snowcap Nimbus Act 2

- [ ] Gritty Columns Act 1
- [ ] Gritty Columns Act 2

- [ ] Fume Shaft Act 1
- [ ] Fume Shaft Act 2

- [ ] Liftoff Gantry Act 1
- [ ] Liftoff Gantry Act 2

- [ ] Spacewalk Act 1
- [ ] Spacewalk Act 2

- [ ] Alien Armageddon Act 1
- [ ] Alien Armageddon Act 2

- [ ] Record Attack emblems (all of them (good luck) )
